services:
  mongoDb:
    image: mongodb/mongodb-community-server:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: user
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: portfolio
    volumes:
      - type: bind
        source: ./data
        target: /data/db

  seed:
    image: node:20-slim
    container_name: seed
    working_dir: /app
    depends_on:
      - mongoDb
    environment:
      MONGO_URI: mongodb://user:pass@mongoDb:27017
      DB_NAME: portfolio
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./tsconfig.json:/app/tsconfig.json
    command: sh -c "npm install typescript ts-node @faker-js/faker mongodb && npx ts-node src/scripts/seed.ts"
    restart: 'no'