services:
  mongodb:
    image: mongodb/mongodb-community-server:7.0-ubi8
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGODB_INITDB_ROOT_USERNAME: user
      MONGODB_INITDB_ROOT_PASSWORD: pass
      MONGODB_INITDB_DATABASE: portfolio
    volumes:
      - mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 5s
      timeout: 5s
      retries: 5

  seed:
    image: node:20-slim
    container_name: seed
    working_dir: /app
    depends_on:
      mongodb:
        condition: service_healthy
    environment:
      MONGO_URI: mongodb://user:pass@mongodb:27017
      DB_NAME: portfolio
      PRODUCT_COLLECTION: "products"
      USER_COLLECTION: "users"
      TARGET_PRODUCT_COUNT: 100
      BACKEND_USER: "dbUser"
      BACKEND_PASSWORD: "Secure1234!"
    volumes:
      - ./src/models/v1/product.models.ts:/app/src/models/v1/product.models.ts
      - ./src/models/v1/user.models.ts:/app/src/models/v1/user.models.ts
      - ./src/scripts/seed.ts:/app/src/scripts/seed.ts
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./tsconfig.json:/app/tsconfig.json
    command: sh -c "npm install typescript ts-node @faker-js/faker mongodb && npx ts-node src/scripts/seed.ts"
    restart: 'no'

  dev:
    image: node:20-slim
    container_name: dev
    working_dir: /app
    depends_on:
      seed:
        condition: service_completed_successfully
    environment:
      MONGO_URI: mongodb://dbUser:Secure1234!@mongodb:27017
      DB_NAME: portfolio
      JWT_SECRET: "Pl.E@k3y!Pl.E@k3y!"
      JWT_OPTIONS: '{"expiresIn":"1h","issuer":"demoBackend"}'
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - ./src:/app/src
      - ./package.json:/app/package.json
      - ./pnpm-lock.yaml:/app/pnpm-lock.yaml
      - ./tsconfig.json:/app/tsconfig.json
    command: sh -c "npm install -g pnpm && pnpm install && pnpm run dev"

volumes:
  mongo-data:
